In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D

# Define the 5x5 input matrix (extracted and corrected from image)
input_matrix = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Reshape to match TensorFlow's expected input shape (batch_size, height, width, channels)
input_tensor = input_matrix.reshape(1, 5, 5, 1)

# Define a 3x3 kernel
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]], dtype=np.float32)

# Convert kernel to TensorFlow format
kernel_tensor = kernel.reshape(3, 3, 1, 1)

# Function to perform convolution with given stride and padding
def apply_convolution(stride, padding):
    input_layer = Input(shape=(5, 5, 1))
    conv_layer = Conv2D(filters=1, kernel_size=(3, 3), strides=stride, padding=padding,
                         kernel_initializer=tf.keras.initializers.Constant(kernel_tensor), use_bias=False)(input_layer)
    model = Model(inputs=input_layer, outputs=conv_layer)
    return model.predict(input_tensor)

# Apply convolution with different parameters
output_valid = apply_convolution(stride=1, padding='valid')
output_same = apply_convolution(stride=1, padding='same')
output_stride_2_valid = apply_convolution(stride=2, padding='valid')
output_stride_2_same = apply_convolution(stride=2, padding='same')

# Print results
print("Output with stride=1, padding='valid':\n", output_valid.squeeze())
print("\nOutput with stride=1, padding='same':\n", output_same.squeeze())
print("\nOutput with stride=2, padding='valid':\n", output_stride_2_valid.squeeze())
print("\nOutput with stride=2, padding='same':\n", output_stride_2_same.squeeze())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 326ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
Output with stride=1, padding='valid':
 [[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

Output with stride=1, padding='same':
 [[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]]

Output with stride=2, padding='valid':
 [[-6. -6.]
 [-6. -6.]]

Output with stride=2, padding='same':
 [[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]]


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D

# Define the 3x3 input matrix
input_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.float32)

# Reshape to match TensorFlow's expected input shape (batch_size, height, width, channels)
input_tensor = input_matrix.reshape(1, 3, 3, 1)

# Define a 3x3 kernel (extracted and corrected from image)
kernel = np.array([[0,  1,  0],
                   [1, -4,  1],
                   [0,  1,  0]], dtype=np.float32)

# Convert kernel to TensorFlow format
kernel_tensor = kernel.reshape(3, 3, 1, 1)

# Function to perform convolution with given stride and padding
def apply_convolution(stride, padding):
    input_layer = Input(shape=(3, 3, 1))
    conv_layer = Conv2D(filters=1, kernel_size=(3, 3), strides=stride, padding=padding,
                         kernel_initializer=tf.keras.initializers.Constant(kernel_tensor), use_bias=False)(input_layer)
    model = Model(inputs=input_layer, outputs=conv_layer)
    return model.predict(input_tensor)

# Apply convolution with different parameters
output_valid = apply_convolution(stride=1, padding='valid')
output_same = apply_convolution(stride=1, padding='same')

# Print results
print("Output with stride=1, padding='valid':\n", output_valid.squeeze())
print("\nOutput with stride=1, padding='same':\n", output_same.squeeze())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 383ms/step
Output with stride=1, padding='valid':
 0.0

Output with stride=1, padding='same':
 [[  2.   1.  -4.]
 [ -3.   0.  -7.]
 [-16. -11. -22.]]


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D

# Define the 3x3 input matrix
input_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.float32)

# Reshape to match TensorFlow's expected input shape (batch_size, height, width, channels)
input_tensor = input_matrix.reshape(1, 3, 3, 1)

# Define a 3x3 kernel (extracted and corrected from image)
kernel = np.array([[0,  1,  0],
                   [1, -4,  1],
                   [0,  1,  0]], dtype=np.float32)

# Convert kernel to TensorFlow format
kernel_tensor = kernel.reshape(3, 3, 1, 1)

# Function to perform convolution with given stride and padding
def apply_convolution(stride, padding):
    input_layer = Input(shape=(3, 3, 1))
    conv_layer = Conv2D(filters=1, kernel_size=(3, 3), strides=stride, padding=padding,
                         kernel_initializer=tf.keras.initializers.Constant(kernel_tensor), use_bias=False)(input_layer)
    model = Model(inputs=input_layer, outputs=conv_layer)
    return model.predict(input_tensor)

# Apply convolution with different parameters
output_valid = apply_convolution(stride=1, padding='valid')
output_same = apply_convolution(stride=1, padding='same')
output_stride_2_valid = apply_convolution(stride=2, padding='valid')
output_stride_2_same = apply_convolution(stride=2, padding='same')

# Print results
print("Output with stride=1, padding='valid':\n", output_valid.squeeze())
print("\nOutput with stride=1, padding='same':\n", output_same.squeeze())
print("\nOutput with stride=2, padding='valid':\n", output_stride_2_valid.squeeze())
print("\nOutput with stride=2, padding='same':\n", output_stride_2_same.squeeze())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step
Output with stride=1, padding='valid':
 0.0

Output with stride=1, padding='same':
 [[  2.   1.  -4.]
 [ -3.   0.  -7.]
 [-16. -11. -22.]]

Output with stride=2, padding='valid':
 0.0

Output with stride=2, padding='same':
 [[  2.  -4.]
 [-16. -22.]]


In [ ]:
import numpy as np
import tensorflow as tf

# Define the input matrix
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define the kernel
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
], dtype=np.float32)

# Reshape input and kernel for TensorFlow
input_tensor = tf.constant(input_matrix.reshape(1, 5, 5, 1))  # Shape: (batch, height, width, channels)
kernel_tensor = tf.constant(kernel.reshape(3, 3, 1, 1))  # Shape: (height, width, in_channels, out_channels)

def perform_convolution(stride, padding):
    output = tf.nn.conv2d(input_tensor, kernel_tensor, strides=[1, stride, stride, 1], padding=padding)
    return output.numpy().squeeze()  # Convert to numpy and remove single dimensions

# Perform convolutions
results = {
    "Stride = 1, Padding = VALID": perform_convolution(1, "VALID"),
    "Stride = 1, Padding = SAME": perform_convolution(1, "SAME"),
    "Stride = 2, Padding = VALID": perform_convolution(2, "VALID"),
    "Stride = 2, Padding = SAME": perform_convolution(2, "SAME"),
}

# Print results
for description, output in results.items():
    print(f"{description}:\n{output}\n")


Stride = 1, Padding = VALID:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Stride = 1, Padding = SAME:
[[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Stride = 2, Padding = VALID:
[[0. 0.]
 [0. 0.]]

Stride = 2, Padding = SAME:
[[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]



Task 1

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image in grayscale
image_path = "/mnt/data/image.png"  # Make sure this path is correct

# Check if the image was loaded successfully
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
if image is None:
    print(f"Error: Could not load image from {image_path}. Please check the file path.")
    exit()  # Exit the script if image loading fails


# Define Sobel filters
sobel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
sobel_y = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

# Apply Sobel filters
edges_x = cv2.filter2D(image, -1, sobel_x)
edges_y = cv2.filter2D(image, -1, sobel_y)

# Display results
plt.figure(figsize=(10, 4))
plt.subplot(1, 3, 1)
plt.imshow(image, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(edges_x, cmap='gray')
plt.title("Sobel X")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(edges_y, cmap='gray')
plt.title("Sobel Y")
plt.axis("off")

plt.show()

Error: Could not load image from /mnt/data/image.png. Please check the file path.


error: OpenCV(4.11.0) /io/opencv/modules/imgproc/src/filter.dispatch.cpp:1528: error: (-215:Assertion failed) !_src.empty() in function 'filter2D'


Task 2

In [ ]:
import tensorflow as tf
import numpy as np

# Create a random 4x4 matrix as input image
input_matrix = np.random.rand(1, 4, 4, 1).astype(np.float32)

# Define Max Pooling and Average Pooling layers
max_pooling = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=2)
avg_pooling = tf.keras.layers.AveragePooling2D(pool_size=(2, 2), strides=2)

# Apply pooling operations
max_pooled = max_pooling(input_matrix).numpy()
avg_pooled = avg_pooling(input_matrix).numpy()

# Print results
print("Original Matrix:\n", input_matrix[0, :, :, 0])
print("Max Pooled Matrix:\n", max_pooled[0, :, :, 0])
print("Average Pooled Matrix:\n", avg_pooled[0, :, :, 0])


Original Matrix:
 [[0.46675086 0.93302983 0.2363711  0.8743808 ]
 [0.63737786 0.03335621 0.6349825  0.9263337 ]
 [0.87682796 0.33702025 0.09155037 0.24988991]
 [0.9294766  0.6527415  0.0327995  0.59941804]]
Max Pooled Matrix:
 [[0.93302983 0.9263337 ]
 [0.9294766  0.59941804]]
Average Pooled Matrix:
 [[0.51762867 0.668017  ]
 [0.6990166  0.24341446]]


Q.4 Task 1


In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Define the AlexNet model
model = Sequential([
    Conv2D(96, (11, 11), strides=4, activation='relu', input_shape=(227, 227, 3)),
    MaxPooling2D(pool_size=(3, 3), strides=2),

    Conv2D(256, (5, 5), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(3, 3), strides=2),

    Conv2D(384, (3, 3), activation='relu', padding='same'),
    Conv2D(384, (3, 3), activation='relu', padding='same'),
    Conv2D(256, (3, 3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(3, 3), strides=2),

    Flatten(),
    Dense(4096, activation='relu'),
    Dropout(0.5),
    Dense(4096, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

# Print model summary
model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 55, 55, 96)          │          34,944 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 27, 27, 96)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 27, 27, 256)         │         614,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 13, 13, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 13, 13, 384)         │         885,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 13, 13, 384)         │       1,327,488 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 13, 13, 256)         │         884,992 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 9216)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 4096)                │      37,752,832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 4096)                │      16,781,312 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │          40,970 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 58,322,314 (222.48 MB)

 Trainable params: 58,322,314 (222.48 MB)

 Non-trainable params: 0 (0.00 B)

Q.4 Task 2

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Add, Input

def residual_block(input_tensor, filters=64):
    x = Conv2D(filters, (3, 3), padding='same', activation='relu')(input_tensor)
    x = Conv2D(filters, (3, 3), padding='same')(x)
    x = Add()([x, input_tensor])
    x = tf.keras.layers.ReLU()(x)
    return x

# Define the AlexNet model
alexnet_model = Sequential([
    Conv2D(96, (11, 11), strides=4, activation='relu', input_shape=(227, 227, 3)),
    MaxPooling2D(pool_size=(3, 3), strides=2),

    Conv2D(256, (5, 5), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(3, 3), strides=2),

    Conv2D(384, (3, 3), activation='relu', padding='same'),
    Conv2D(384, (3, 3), activation='relu', padding='same'),
    Conv2D(256, (3, 3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(3, 3), strides=2),

    Flatten(),
    Dense(4096, activation='relu'),
    Dropout(0.5),
    Dense(4096, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

# Print AlexNet model summary
print("AlexNet Model Summary:")
alexnet_model.summary()

# Define the ResNet-like model
input_layer = Input(shape=(224, 224, 3))
x = Conv2D(64, (7, 7), strides=2, padding='same', activation='relu')(input_layer)
x = residual_block(x)
x = residual_block(x)
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
output_layer = Dense(10, activation='softmax')(x)

resnet_model = Model(inputs=input_layer, outputs=output_layer)

# Print ResNet-like model summary
print("ResNet-like Model Summary:")
resnet_model.summary()

AlexNet Model Summary:


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_5 (Conv2D)                    │ (None, 55, 55, 96)          │          34,944 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 27, 27, 96)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 27, 27, 256)         │         614,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 13, 13, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 13, 13, 384)         │         885,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 13, 13, 384)         │       1,327,488 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 13, 13, 256)         │         884,992 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_5 (MaxPooling2D)       │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 9216)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 4096)                │      37,752,832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 4096)                │      16,781,312 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │          40,970 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 58,322,314 (222.48 MB)

 Trainable params: 58,322,314 (222.48 MB)

 Non-trainable params: 0 (0.00 B)

ResNet-like Model Summary:


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2             │ (None, 224, 224, 3)    │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_10 (Conv2D)        │ (None, 112, 112, 64)   │          9,472 │ input_layer_2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_11 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_10[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_12 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_11[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add (Add)                 │ (None, 112, 112, 64)   │              0 │ conv2d_12[0][0],       │
│                           │                        │                │ conv2d_10[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ re_lu (ReLU)              │ (None, 112, 112, 64)   │              0 │ add[0][0]              │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_13 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ re_lu[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_14 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_13[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add_1 (Add)               │ (None, 112, 112, 64)   │              0 │ conv2d_14[0][0],       │
│                           │                        │                │ re_lu[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ re_lu_1 (ReLU)            │ (None, 112, 112, 64)   │              0 │ add_1[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ flatten_2 (Flatten)       │ (None, 802816)         │              0 │ re_lu_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_6 (Dense)           │ (None, 128)            │    102,760,576 │ flatten_2[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_7 (Dense)           │ (None, 10)             │          1,290 │ dense_6[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 102,919,050 (392.61 MB)

 Trainable params: 102,919,050 (392.61 MB)

 Non-trainable params: 0 (0.00 B)